# Generated by Django 4.1.2 on 2022-10-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='completion_data',
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=40),
        ),
    ]
