# Generated by Django 4.1.2 on 2022-10-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_remove_about_avatar_about_link_about_link_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='num',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skill',
        ),
        migrations.AddField(
            model_name='skills',
            name='skill_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='skills',
            name='workflow',
            field=models.CharField(default='', max_length=50),
        ),
    ]
