# Generated by Django 4.1.2 on 2022-10-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_remove_skills_num_remove_skills_skill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='mini_about',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name',
        ),
        migrations.AddField(
            model_name='about',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='about',
            name='first_name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='about',
            name='second_name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
