# Generated by Django 4.1.2 on 2022-11-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_remove_about_mini_about_remove_about_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skill_name',
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=60),
        ),
    ]
